// Motor de generación: selección de tema, programación (pura, tz-aware) y el
// pipeline de generateDraft con dependencias simuladas (sin red ni LLM real).

import { test } from "node:test";
import assert from "node:assert/strict";

import { selectNextTopic, usageFromPosts } from "../src/lib/automation/topic.js";
import { createAttemptLimiter, shouldRunNow, scheduleStateFromPosts, weekdayInTz } from "../src/lib/automation/schedule.js";
import { generateDraft } from "../src/lib/automation/generate.js";
import { blogAutomationSchema } from "../src/lib/blogAutomationSchema.js";

const cfg = (over: Record<string, unknown> = {}) =>
  blogAutomationSchema.parse({
    enabled: true,
    topics: ["X"],
    schedule: { perWeek: 3, days: ["tue"], time: "09:00", timezone: "America/Guayaquil" },
    ...over,
  });

// ── Selección de tema ────────────────────────────────────────────────────────
test("selectNextTopic: elige el menos usado y desempata por prioridad", () => {
  assert.equal(selectNextTopic(["A", "B", "C"], {}), "A"); // todos 0 → el primero
  assert.equal(selectNextTopic(["A", "B", "C"], { A: 2, B: 0, C: 1 }), "B");
  assert.equal(selectNextTopic(["A", "B", "C"], { A: 1, B: 1, C: 0 }), "C");
  assert.equal(selectNextTopic(["A", "B"], { A: 1, B: 1 }), "A"); // empate → prioridad
  assert.equal(selectNextTopic([], {}), null);
});

test("usageFromPosts cuenta por tema solo los auto-generados", () => {
  const u = usageFromPosts([
    { autoGenerated: true, automationTopic: "A" },
    { autoGenerated: true, automationTopic: "A" },
    { autoGenerated: false, automationTopic: "B" },
    { automationTopic: "C" },
  ]);
  assert.deepEqual(u, { A: 2 });
});

// ── Programación (2026-07-21 es martes; Guayaquil = UTC-5) ────────────────────
test("weekdayInTz da el día correcto en la zona horaria", () => {
  assert.equal(weekdayInTz(new Date("2026-07-21T14:00:00Z"), "America/Guayaquil"), "tue");
});

test("shouldRunNow respeta día, hora, cupo y 'ya generó hoy'", () => {
  const tueAM = new Date("2026-07-21T14:05:00Z"); // 09:05 local
  assert.equal(shouldRunNow(cfg(), tueAM, { weekCount: 0, lastRunDay: null }).run, true);
  assert.equal(shouldRunNow(cfg(), new Date("2026-07-21T13:00:00Z"), { weekCount: 0, lastRunDay: null }).run, false); // antes de hora
  assert.equal(shouldRunNow(cfg(), new Date("2026-07-22T14:05:00Z"), { weekCount: 0, lastRunDay: null }).run, false); // miércoles
  assert.equal(shouldRunNow(cfg(), tueAM, { weekCount: 0, lastRunDay: "2026-07-21" }).run, false); // ya hoy
  assert.equal(shouldRunNow(cfg(), tueAM, { weekCount: 3, lastRunDay: null }).run, false); // cupo
  assert.equal(shouldRunNow(cfg({ enabled: false }), tueAM, { weekCount: 0, lastRunDay: null }).run, false);
  assert.equal(shouldRunNow(cfg({ topics: [] }), tueAM, { weekCount: 0, lastRunDay: null }).run, false); // sin temas
});

test("scheduleStateFromPosts deriva cupo semanal y último día", () => {
  const now = new Date("2026-07-21T12:00:00Z");
  const st = scheduleStateFromPosts(
    [
      { autoGenerated: true, date: "2026-07-20" },
      { autoGenerated: true, date: "2026-07-18" },
      { autoGenerated: true, date: "2026-06-01" }, // fuera de los 7 días
      { autoGenerated: false, date: "2026-07-21" }, // no auto
    ],
    now,
  );
  assert.equal(st.weekCount, 2);
  assert.equal(st.lastRunDay, "2026-07-20");
});

// ── Pipeline generateDraft ───────────────────────────────────────────────────
test("generateDraft: crea un BORRADOR (draft + autoGenerated), nunca publica", async () => {
  // Acumulador en vez de variable anulable: TypeScript no sigue las asignaciones
  // hechas dentro de un callback, y además así se afirma el invariante real del
  // sistema: una corrida = UN commit.
  const commits: Array<{ files: Array<{ path: string; content: string }>; msg: string }> = [];
  const res = await generateDraft(cfg({ topics: ["Becas"] }), {
    now: () => new Date("2026-07-21T14:00:00Z"),
    research: async () => ({ sources: [], competitors: { competitors: [], recentTitles: [], gaps: [] }, generatedAt: "" }),
    listPosts: async () => [],
    llm: async ({ topic }) => ({ title: `Sobre ${topic}`, excerpt: "resumen", body: "## Hola\ncuerpo", cat: "General", imgAlt: "alt", imagePrompt: "p" }),
    commit: async (files, msg) => { commits.push({ files, msg }); },
  });
  assert.equal(res.ok, true);
  assert.equal(res.topic, "Becas");
  assert.ok(res.slug?.startsWith("sobre-becas-2026-07-21"));
  assert.equal(commits.length, 1, "una corrida debe dejar exactamente un commit");
  const file = commits[0].files[0];
  assert.ok(file.path.startsWith("src/content/articulos/"));
  assert.match(file.content, /draft: true/);
  assert.match(file.content, /autoGenerated: true/);
  assert.match(file.content, /automationTopic: "Becas"/);
});

test("generateDraft: una fuente requerida fallida aborta sin llamar al LLM ni commitear", async () => {
  let committed = false;
  let llmCalled = false;
  const res = await generateDraft(cfg({ topics: ["X"] }), {
    now: () => new Date("2026-07-21T14:00:00Z"),
    research: async () => ({
      sources: [{ url: "https://req.com", ok: false, required: true, items: [], error: "boom" }],
      competitors: { competitors: [], recentTitles: [], gaps: [] },
      generatedAt: "",
    }),
    listPosts: async () => [],
    llm: async () => { llmCalled = true; throw new Error("no debería llamarse"); },
    commit: async () => { committed = true; },
  });
  assert.equal(res.ok, false);
  assert.match(res.reason ?? "", /requerida/);
  assert.equal(llmCalled, false);
  assert.equal(committed, false);
});

// ── Portada en el MISMO commit que el .md ────────────────────────────────────
test("generateDraft: la portada se commitea junto al .md, no aparte", async () => {
  let committed: { files: Array<{ path: string; content: string }>; msg: string } | null = null;
  const res = await generateDraft(cfg({ topics: ["Becas"] }), {
    now: () => new Date("2026-07-21T14:00:00Z"),
    research: async () => ({ sources: [], competitors: { competitors: [], recentTitles: [], gaps: [] }, generatedAt: "" }),
    listPosts: async () => [],
    llm: async ({ topic }) => ({ title: `Sobre ${topic}`, excerpt: "r", body: "cuerpo", cat: "General", imgAlt: "alt", imagePrompt: "p" }),
    generateCover: async () => ({ path: "/uploads/portada-abc.webp", file: { path: "public/uploads/portada-abc.webp", content: "AAAA", encoding: "base64" as const } }),
    commit: async (files, msg) => { committed = { files, msg }; },
  });
  assert.equal(res.ok, true);
  // Un solo commit con los DOS archivos: si fallara, no queda la imagen huérfana.
  assert.equal(committed!.files.length, 2);
  const paths = committed!.files.map((f) => f.path).sort();
  assert.deepEqual(paths, ["public/uploads/portada-abc.webp", `src/content/articulos/${res.slug}.md`].sort());
  assert.match(committed!.files.find((f) => f.path.endsWith(".md"))!.content, /img: "\/uploads\/portada-abc\.webp"/);
});

test("generateDraft: si la portada falla, sigue con el placeholder y commitea solo el .md", async () => {
  let committed: { files: Array<{ path: string; content: string }> } | null = null;
  const res = await generateDraft(cfg({ topics: ["Becas"] }), {
    now: () => new Date("2026-07-21T14:00:00Z"),
    research: async () => ({ sources: [], competitors: { competitors: [], recentTitles: [], gaps: [] }, generatedAt: "" }),
    listPosts: async () => [],
    llm: async () => ({ title: "T", excerpt: "r", body: "cuerpo", cat: "General", imgAlt: "alt", imagePrompt: "p" }),
    generateCover: async () => { throw new Error("proveedor de imágenes caído"); },
    commit: async (files) => { committed = { files }; },
  });
  // El texto ya está pagado: no se tira por no tener imagen.
  assert.equal(res.ok, true);
  assert.equal(committed!.files.length, 1);
  assert.match(committed!.files[0].content, /blog-placeholder\.webp/);
});

// ── Freno de intentos (el fallo caro que se reintentaba cada 60 s) ───────────
test("el freno acota los intentos de un día fallido a unos pocos, no a cientos", async () => {
  const lim = createAttemptLimiter(3, 15 * 60_000);
  const t0 = new Date("2026-07-21T09:00:00Z").getTime();
  const day = "2026-07-21";
  // Simula la realidad anterior: el tick corre cada 60 s desde las 09:00 hasta
  // medianoche y la generación SIEMPRE falla (no crea post → nada la detiene).
  let concedidos = 0;
  const ticks = 15 * 60; // 15 horas de ticks por minuto
  for (let i = 0; i < ticks; i++) {
    if (lim.tryAcquire(new Date(t0 + i * 60_000), day)) concedidos += 1;
  }
  assert.equal(ticks, 900, "el escenario son 900 ticks en la tarde");
  assert.equal(concedidos, 3, "solo 3 corridas de pago, no 900");
});

test("el freno espacia los reintentos: dos ticks seguidos no gastan dos veces", () => {
  const lim = createAttemptLimiter(3, 15 * 60_000);
  const t0 = new Date("2026-07-21T09:00:00Z").getTime();
  assert.equal(lim.tryAcquire(new Date(t0), "2026-07-21"), true);
  assert.equal(lim.tryAcquire(new Date(t0 + 60_000), "2026-07-21"), false, "1 min después: aún en espera");
  assert.equal(lim.tryAcquire(new Date(t0 + 15 * 60_000), "2026-07-21"), true, "15 min después: se reintenta");
});

test("el freno reparte cupo nuevo cada día", () => {
  const lim = createAttemptLimiter(1, 0);
  const now = new Date("2026-07-21T09:00:00Z");
  assert.equal(lim.tryAcquire(now, "2026-07-21"), true);
  assert.equal(lim.tryAcquire(now, "2026-07-21"), false, "cupo agotado hoy");
  assert.equal(lim.tryAcquire(now, "2026-07-22"), true, "mañana empieza de cero");
});
