import type { BlogAutomationConfig } from "../blogAutomationSchema.js";
import { gatherResearch, requiredSourcesFailed, researchToPrompt, type ResearchBundle, type ResearchDeps } from "../research/index.js";
import { blogFrontmatterSchema, buildBlogMarkdown, slugify, BLOG_CATEGORIES } from "../markdown.js";
import { postPath } from "../posts.js";
import { selectNextTopic, usageFromPosts } from "./topic.js";
import { dayKeyInTz } from "./schedule.js";

// Lo que el LLM debe devolver para un borrador.
export interface DraftContent {
  title: string;
  excerpt: string;
  body: string; // Markdown
  cat: string;
  imgAlt: string;
  imagePrompt: string; // para generar la portada
}

export interface GenerateDeps {
  // Inyectables para pruebas. En producción se pasan los reales (Anthropic, GitHub…).
  llm: (input: { topic: string; researchText: string; config: BlogAutomationConfig }) => Promise<DraftContent>;
  listPosts: () => Promise<Array<{ autoGenerated?: boolean; automationTopic?: string; date: string }>>;
  commit: (files: Array<{ path: string; content: string; encoding?: "utf-8" | "base64" }>, message: string) => Promise<void>;
  // Portada opcional. Devuelve la ruta pública Y el archivo, para commitearlo
  // JUNTO al .md: si se commiteara aparte y luego fallara el .md, la imagen
  // quedaría huérfana en el repo (y el siguiente intento generaría otra).
  generateCover?: (prompt: string) => Promise<{ path: string; file: { path: string; content: string; encoding?: "utf-8" | "base64" } }>;
  research?: (config: BlogAutomationConfig) => Promise<ResearchBundle>;
  researchDeps?: ResearchDeps;
  now?: () => Date;
}

export interface GenerateResult {
  ok: boolean;
  slug?: string;
  topic?: string;
  title?: string;
  reason?: string;
}

const PLACEHOLDER_IMG = "/uploads/blog-placeholder.webp";

// Genera UN borrador de blog completo y lo guarda como draft (NUNCA publica):
// elige tema → investiga → redacta con el LLM → escribe .md (draft:true,
// autoGenerated:true). Si una fuente REQUERIDA falla, no genera.
export async function generateDraft(config: BlogAutomationConfig, deps: GenerateDeps): Promise<GenerateResult> {
  const now = (deps.now ?? (() => new Date()))();

  // 1) Tema por prioridad/rotación.
  const posts = await deps.listPosts();
  const topic = selectNextTopic(config.topics, usageFromPosts(posts));
  if (!topic) return { ok: false, reason: "no hay temas configurados" };

  // 2) Investigación (fuentes + competencia). Regla dura: requerida que falla → aborta.
  const bundle = deps.research ? await deps.research(config) : await gatherResearch(config, deps.researchDeps);
  const failed = requiredSourcesFailed(bundle);
  if (failed.length) {
    return { ok: false, topic, reason: `fuente(s) requerida(s) sin datos: ${failed.map((f) => f.url).join(", ")}` };
  }

  // 3) Redacción con el LLM.
  const draft = await deps.llm({ topic, researchText: researchToPrompt(bundle), config });
  const cat = BLOG_CATEGORIES.includes(draft.cat) ? draft.cat : BLOG_CATEGORIES[0];

  // 4) Portada (opcional) + escritura del borrador. Si la generación de la
  // imagen falla, se sigue con el placeholder: el texto ya está pagado y vale.
  const cover = deps.generateCover ? await deps.generateCover(draft.imagePrompt).catch(() => null) : null;
  const img = cover?.path ?? PLACEHOLDER_IMG;
  const dateStr = dayKeyInTz(now, config.schedule.timezone);
  const slug = `${slugify(draft.title) || "borrador"}-${dateStr}`.slice(0, 80);
  const fm = blogFrontmatterSchema.parse({
    title: draft.title.slice(0, 120),
    cat,
    date: dateStr,
    excerpt: draft.excerpt.slice(0, 280),
    img,
    imgAlt: draft.imgAlt?.slice(0, 200) || undefined,
    draft: true, // NUNCA se auto-publica
    autoGenerated: true,
    automationTopic: topic,
  });
  const md = buildBlogMarkdown(fm, draft.body);
  // Un solo commit con el .md y su portada: o entran los dos, o no entra nada.
  await deps.commit(
    [{ path: postPath(slug), content: md }, ...(cover ? [cover.file] : [])],
    `automatización: borrador "${fm.title}" (tema: ${topic}) — para revisión`,
  );
  return { ok: true, slug, topic, title: fm.title };
}
