import type { BlogAutomationConfig } from "../blogAutomationSchema.js";

// Lógica de programación (pura, con la zona horaria de la config). El motor hace
// "tick" cada minuto; estas funciones deciden si toca generar AHORA.

// Día de la semana (mon..sun) en una zona horaria dada.
export function weekdayInTz(date: Date, tz: string): string {
  return new Intl.DateTimeFormat("en-US", { timeZone: tz, weekday: "short" }).format(date).slice(0, 3).toLowerCase();
}

// Minuto del día (0–1439) en una zona horaria dada.
export function minutesOfDayInTz(date: Date, tz: string): number {
  const parts = new Intl.DateTimeFormat("en-US", { timeZone: tz, hour: "2-digit", minute: "2-digit", hour12: false }).formatToParts(date);
  const h = Number(parts.find((p) => p.type === "hour")?.value ?? "0") % 24;
  const m = Number(parts.find((p) => p.type === "minute")?.value ?? "0");
  return h * 60 + m;
}

// Día local (YYYY-MM-DD) en una zona horaria dada.
export function dayKeyInTz(date: Date, tz: string): string {
  return new Intl.DateTimeFormat("en-CA", { timeZone: tz, year: "numeric", month: "2-digit", day: "2-digit" }).format(date);
}

export interface ScheduleState {
  // Cuántos blogs auto-generados en los últimos 7 días (para el cupo semanal).
  weekCount: number;
  // Día (YYYY-MM-DD, tz) del último auto-generado, o null.
  lastRunDay: string | null;
}

export interface RunDecision {
  run: boolean;
  reason: string;
}

// ¿Toca generar ahora? Dispara UNA vez por día preferido, a partir de la hora,
// respetando el cupo semanal. Robusto a ticks perdidos (no exige el minuto exacto).
export function shouldRunNow(config: BlogAutomationConfig, now: Date, state: ScheduleState): RunDecision {
  if (!config.enabled) return { run: false, reason: "automatización desactivada" };
  if (!config.topics.length) return { run: false, reason: "no hay temas configurados" };
  const tz = config.schedule.timezone;
  const dow = weekdayInTz(now, tz);
  if (!config.schedule.days.includes(dow as BlogAutomationConfig["schedule"]["days"][number])) {
    return { run: false, reason: `hoy (${dow}) no es un día preferido` };
  }
  const [h, m] = config.schedule.time.split(":").map(Number);
  if (minutesOfDayInTz(now, tz) < h * 60 + m) return { run: false, reason: "aún no es la hora" };
  const today = dayKeyInTz(now, tz);
  if (state.lastRunDay === today) return { run: false, reason: "ya se generó hoy" };
  if (state.weekCount >= config.schedule.perWeek) return { run: false, reason: "cupo semanal alcanzado" };
  return { run: true, reason: "toca generar" };
}

// Deriva el estado de programación desde los posts (sin base de datos): cuenta
// los auto-generados de los últimos 7 días y toma la fecha del más reciente.
export function scheduleStateFromPosts(posts: Array<{ autoGenerated?: boolean; date: string }>, now: Date): ScheduleState {
  const auto = posts.filter((p) => p.autoGenerated);
  const weekAgo = now.getTime() - 7 * 86_400_000;
  const weekCount = auto.filter((p) => {
    const t = new Date(p.date).getTime();
    return !Number.isNaN(t) && t >= weekAgo;
  }).length;
  const dates = auto.map((p) => p.date).filter(Boolean).sort();
  return { weekCount, lastRunDay: dates.length ? dates[dates.length - 1] : null };
}

// ── Freno de intentos ────────────────────────────────────────────────────────
// El estado "ya se generó hoy" se deriva de los POSTS, así que un intento que
// FALLA no deja rastro: shouldRunNow vuelve a decir "toca generar" y el tick de
// cada 60 s lo reintenta hasta medianoche. Cuando el fallo llega después de
// redactar (GitHub caído al commitear, por ejemplo) cada vuelta paga modelo +
// imagen: cientos de corridas invisibles en una tarde.
//
// Esto cuenta INTENTOS, no éxitos: unos pocos por día y espaciados, para tolerar
// un fallo pasajero sin convertirlo en una factura.
export interface AttemptLimiter {
  /** ¿Se puede intentar ahora? Si sí, lo anota (consume un intento). */
  tryAcquire(now: Date, dayKey: string): boolean;
  /** Intentos consumidos en el día en curso (diagnóstico y pruebas). */
  attempts(): number;
  reset(): void;
}

export function createAttemptLimiter(maxPerDay: number, backoffMs: number): AttemptLimiter {
  let day: string | null = null;
  let used = 0;
  let lastAt = 0;
  return {
    tryAcquire(now, dayKey) {
      if (day !== dayKey) { day = dayKey; used = 0; lastAt = 0; } // día nuevo, cupo nuevo
      if (used >= maxPerDay) return false;
      if (lastAt && now.getTime() - lastAt < backoffMs) return false; // aún en espera
      used += 1;
      lastAt = now.getTime();
      return true;
    },
    attempts: () => used,
    reset() { day = null; used = 0; lastAt = 0; },
  };
}
