// Selección de tema por PRIORIDAD/ROTACIÓN (puro). El orden de `topics` es la
// prioridad; se elige el tema MENOS usado y se desempata por prioridad (el
// primero del array). El uso se deriva de los posts auto-generados.

export function usageFromPosts(posts: Array<{ autoGenerated?: boolean; automationTopic?: string }>): Record<string, number> {
  const usage: Record<string, number> = {};
  for (const p of posts) {
    if (p.autoGenerated && p.automationTopic) {
      usage[p.automationTopic] = (usage[p.automationTopic] ?? 0) + 1;
    }
  }
  return usage;
}

export function selectNextTopic(topics: string[], usageByTopic: Record<string, number>): string | null {
  if (!topics.length) return null;
  let best = topics[0];
  let bestCount = usageByTopic[best] ?? 0;
  for (const t of topics) {
    const c = usageByTopic[t] ?? 0;
    if (c < bestCount) { best = t; bestCount = c; } // "<" estricto: los empates conservan el de mayor prioridad
  }
  return best;
}
