import { z } from "zod";
import { config } from "../config.js";
import { BLOG_CATEGORIES as SITE_BLOG_CATEGORIES } from "../generated/schema-manifest.js";

// Categorías de blog: FUENTE ÚNICA en el sitio (astro-web/src/content/blog-categories.ts),
// traídas por codegen al manifiesto. Este esquema y la herramienta del agente
// (blogTools) las derivan de ahí — nunca se mantienen a mano en el panel.
export const BLOG_CATEGORIES = SITE_BLOG_CATEGORIES as [string, ...string[]];

// Construye un archivo Markdown de blog con frontmatter válido para la colección
// "blog" de Astro (ver astro-web/src/content/config.ts). El esquema espeja el de
// Astro, así el build nunca recibe un frontmatter inválido.
export const blogFrontmatterSchema = z.object({
  title: z.string().max(120),
  // La categoría se valida contra la lista VIVA (assertCategory) además del
  // enum del codegen, para que las categorías editadas desde el panel apliquen
  // sin regenerar el manifiesto.
  cat: z.string().min(1),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Fecha en formato YYYY-MM-DD"),
  excerpt: z.string().max(280),
  img: z.string().min(1),
  // Texto alternativo de la portada (accesibilidad + SEO). Opcional: el sitio
  // usa el título si falta.
  imgAlt: z.string().max(200).optional(),
  draft: z.boolean().default(true),
  author: z.string().default(config.client.authorDefault),
  tags: z.array(z.string()).default([]),
  // Marcado por la automatización (para la cola de revisión + rotación de temas).
  autoGenerated: z.boolean().default(false),
  automationTopic: z.string().optional(),
});

// Valida la categoría contra una lista concreta (la viva del sitio, o la del
// codegen como respaldo). Lanza un error claro con las opciones válidas.
export function assertCategory(cat: string, _categories: readonly string[] = BLOG_CATEGORIES): void {
  /* En el kit la categoría es texto libre (`categoria` del artículo). El
     manifiesto de IIDEA no aplica. Vacía sí se rechaza. */
  if (!String(cat ?? "").trim()) throw new Error("La categoría no puede estar vacía");
}

export type BlogFrontmatter = z.infer<typeof blogFrontmatterSchema>;

function yamlString(s: string): string {
  // Cita siempre para evitar problemas con ":" y caracteres especiales.
  return `"${s.replace(/"/g, '\\"')}"`;
}

export function buildBlogMarkdown(fm: BlogFrontmatter, body: string): string {
  const tags = fm.tags.length ? `[${fm.tags.map(yamlString).join(", ")}]` : "[]";
  const front = [
    "---",
    `title: ${yamlString(fm.title)}`,
    `cat: ${yamlString(fm.cat)}`,
    `date: ${fm.date}`,
    `excerpt: ${yamlString(fm.excerpt)}`,
    `img: ${yamlString(fm.img)}`,
    ...(fm.imgAlt ? [`imgAlt: ${yamlString(fm.imgAlt)}`] : []),
    `draft: ${fm.draft}`,
    `author: ${yamlString(fm.author)}`,
    `tags: ${tags}`,
    // Solo se escriben cuando aplican, para no ensuciar las entradas normales.
    ...(fm.autoGenerated ? ["autoGenerated: true"] : []),
    ...(fm.automationTopic ? [`automationTopic: ${yamlString(fm.automationTopic)}`] : []),
    "---",
    "",
  ].join("\n");
  return front + body.trim() + "\n";
}

// Convierte un título en un slug de archivo (sin acentos, minúsculas, guiones).
//
// El recorte a 60 caracteres vuelve atrás hasta el último guion: cortar a
// ciegas dejaba URLs partidas a mitad de palabra ("...da-el-salto-a-un-mej"),
// que se ven rotas en los resultados de búsqueda y al compartirlas. Si la
// primera palabra ya pasa de 60, se corta igual — un slug largo es peor que uno
// feo. No toca los slugs YA publicados: son nombres de archivo en el repo, y
// renombrarlos exigiría redirecciones 301.
export function slugify(title: string): string {
  const base = title
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "") // elimina acentos/diacríticos
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  if (base.length <= 60) return base;
  const corte = base.slice(0, 60);
  const ultimo = corte.lastIndexOf("-");
  return (ultimo > 0 ? corte.slice(0, ultimo) : corte).replace(/-+$/, "");
}
